import { faPencil, 
  faPaperclip,
  faChartSimple,
  faLock,
  faFile,
  faUser,
  faCalendar,
  faBullhorn, 
  faScroll,
  faCodePullRequest,
  faEye,
  faEyeSlash,
  faArrowRightFromBracket,
  faCaretDown,
  faSortDown,
  faFaceSadTear,
  faBars,
  faCaretLeft,
  faFileArrowDown,
  faFilePdf,
  faXmark,
  faComment,
  faCheck,
  faThumbsUp,
  faCaretRight,
  faHouse,
  faTrash,
  faPlus, } from '@fortawesome/free-solid-svg-icons';

export const icons = {
  reports: faScroll,
  paperclip: faPaperclip,
  calendar: faCalendar,
  pencil: faPencil,
  chart: faChartSimple,
  lock: faLock,
  file: faFile,
  user: faUser,
  horn: faBullhorn,
  requests: faCodePullRequest,
  eye: faEye,
  eyeslash: faEyeSlash,
  logout: faArrowRightFromBracket,
  v: faCaretDown,
  left: faCaretLeft,
  right: faCaretRight,
  down: faSortDown,
  sad: faFaceSadTear,
  burger: faBars,
  download: faFileArrowDown,
  pdf: faFilePdf,
  close: faXmark,
  comments: faComment,
  check: faCheck,
  like: faThumbsUp,
  house: faHouse,
  trash: faTrash,
  plus: faPlus
};
